const sampleRawDrinkData = {
  "drinks": [
      {
          "idDrink": "17827",
          "strDrink": "Old Pal",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Cocktail",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Nick and Nora Glass",
          "strInstructions": "Chill cocktail glass. Add ingredients to a mixing glass, and fill 2/3 full with ice. Stir about 20 seconds. Empty cocktail glass and strain into the glass. Garnish with a twist of lemon peel.",
          "strInstructionsES": null,
          "strInstructionsDE": "Cocktailglas kühl stellen. Geben Sie die Zutaten in ein Mischglas und füllen Sie 2/3 der Zutaten mit Eis. Etwa 20 Sekunden umrühren. Cocktailglas in das Glas abseihen. Mit einer Zitronenspirale garnieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Raffredda un bicchiere da cocktail.\r\nAggiungere gli ingredienti in un mixing glass e riempire con 2/3 di ghiaccio.\r\nMescola per circa 20 secondi.\r\nFiltrare nel bicchiere.\r\nGuarnire con una scorza di limone.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/x03td31521761009.jpg",
          "strIngredient1": "Rye whiskey",
          "strIngredient2": "Campari",
          "strIngredient3": "Dry Vermouth",
          "strIngredient4": null,
          "strIngredient5": null,
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "2 oz",
          "strMeasure2": "1 oz",
          "strMeasure3": "1 oz",
          "strMeasure4": null,
          "strMeasure5": null,
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2018-03-22 23:23:30"
      },
      {
          "idDrink": "17199",
          "strDrink": "Golden dream",
          "strDrinkAlternate": null,
          "strTags": "IBA,ContemporaryClassic",
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": "Contemporary Classics",
          "strAlcoholic": "Alcoholic",
          "strGlass": "Cocktail glass",
          "strInstructions": "Shake with cracked ice. Strain into glass and serve.",
          "strInstructionsES": null,
          "strInstructionsDE": "Mit gebrochenem Eis schütteln. In ein Glas abseihen und servieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Shakerare con ghiaccio tritato.\r\nFiltrare nel bicchiere e servire.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qrot6j1504369425.jpg",
          "strIngredient1": "Galliano",
          "strIngredient2": "Triple Sec",
          "strIngredient3": "orange juice",
          "strIngredient4": "Cream",
          "strIngredient5": null,
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "2 parts",
          "strMeasure2": "2 parts",
          "strMeasure3": "2 parts",
          "strMeasure4": "1 part",
          "strMeasure5": null,
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2017-09-02 17:23:45"
      },
      {
          "idDrink": "11001",
          "strDrink": "Old Fashioned",
          "strDrinkAlternate": null,
          "strTags": "IBA,Classic,Alcoholic,Expensive,Savory",
          "strVideo": "https://www.youtube.com/watch?v=YsE_igrPXZs",
          "strCategory": "Cocktail",
          "strIBA": "Unforgettables",
          "strAlcoholic": "Alcoholic",
          "strGlass": "Old-fashioned glass",
          "strInstructions": "Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved.\r\nFill the glass with ice cubes and add whiskey.\r\n\r\nGarnish with orange twist, and a cocktail cherry.",
          "strInstructionsES": null,
          "strInstructionsDE": "Zuckerwürfel in ein old fashioned Glas geben und mit Bitterstoff sättigen, einen Schuss Wasser hinzufügen. Vermischen, bis sie sich auflösen.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Mettere la zolletta di zucchero nel bicchiere vecchio stile e saturare con il bitter, aggiungere un goccio di acqua naturale.\r\nPestare finché non si scioglie.\r\nRiempi il bicchiere con cubetti di ghiaccio e aggiungi il whisky.\r\nGuarnire con una scorza d'arancia e una ciliegina al maraschino.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg",
          "strIngredient1": "Bourbon",
          "strIngredient2": "Angostura bitters",
          "strIngredient3": "Sugar",
          "strIngredient4": "Water",
          "strIngredient5": null,
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "4.5 cL",
          "strMeasure2": "2 dashes",
          "strMeasure3": "1 cube",
          "strMeasure4": "dash",
          "strMeasure5": null,
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": "https://www.thecocktaildb.com/drink/11001-Old-Fashioned-Cocktail",
          "strImageAttribution": "Dave M",
          "strCreativeCommonsConfirmed": "Yes",
          "dateModified": "2016-11-04 09:46:42"
      },
      {
          "idDrink": "12089",
          "strDrink": "Rum Old-fashioned",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Old-fashioned glass",
          "strInstructions": "Stir powdered sugar, water, and bitters in an old-fashioned glass. When sugar has dissolved add ice cubes and light rum. Add the twist of lime peel, float 151 proof rum on top, and serve.",
          "strInstructionsES": null,
          "strInstructionsDE": "Puderzucker, Wasser und Bitter in einem old-fashioned Glas verrühren. Wenn sich der Zucker aufgelöst hat, Eiswürfel und leichten Rum hinzufügen. Die Limettenspirale hinzufügen, 151er Rum darauf verteilen und servieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Mescolare lo zucchero, l'acqua e il bitter in un bicchiere vecchio stile. Quando lo zucchero si sarà sciolto aggiungere i cubetti di ghiaccio e il rum chiaro. Aggiungere la scorza di lime, far galleggiare sopra 151 rum e servire.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/otn2011504820649.jpg",
          "strIngredient1": "Light rum",
          "strIngredient2": "151 proof rum",
          "strIngredient3": "Powdered sugar",
          "strIngredient4": "Bitters",
          "strIngredient5": "Water",
          "strIngredient6": "Lime peel",
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "1 1/2 oz ",
          "strMeasure2": "1 tsp ",
          "strMeasure3": "1/2 tsp ",
          "strMeasure4": "1 dash ",
          "strMeasure5": "1 tsp ",
          "strMeasure6": "Twist of ",
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2017-09-07 22:44:09"
      },
      {
          "idDrink": "11145",
          "strDrink": "Classic Old-Fashioned",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Old-fashioned glass",
          "strInstructions": "In an old-fashioned glass, muddle the bitters and water into the sugar cube, using the back of a teaspoon. Almost fill the glass with ice cubes and add the bourbon. Garnish with the orange slice and the cherry. Serve with a swizzle stick.",
          "strInstructionsES": null,
          "strInstructionsDE": "In einem old-fashioned Glas die Bitter und das Wasser mit der Rückseite eines Teelöffels in den Zuckerwürfel mischen. Füllen Sie das Glas fast mit Eiswürfeln und fügen Sie den Bourbon hinzu. Mit der Orangenscheibe und der Kirsche garnieren. Mit einem Quirlstab servieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "In un bicchiere vecchio stile, mescola il bitter e l'acqua nella zolletta di zucchero. Riempite quasi il bicchiere di cubetti di ghiaccio e aggiungete il bourbon. Servire con un bastoncino di zucchero. Guarnire con la fetta d'arancia e la ciliegia.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/w8cxqv1582485254.jpg",
          "strIngredient1": "Bitters",
          "strIngredient2": "Water",
          "strIngredient3": "Sugar",
          "strIngredient4": "Bourbon",
          "strIngredient5": "Orange",
          "strIngredient6": "Maraschino cherry",
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "3 dashes ",
          "strMeasure2": "1 tsp ",
          "strMeasure3": "1 ",
          "strMeasure4": "3 oz ",
          "strMeasure5": "1 ",
          "strMeasure6": "1 ",
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "Yes",
          "dateModified": "2017-09-02 16:29:33"
      },
      {
          "idDrink": "12720",
          "strDrink": "Kill the cold Smoothie",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Other / Unknown",
          "strIBA": null,
          "strAlcoholic": "Non alcoholic",
          "strGlass": "Highball glass",
          "strInstructions": "Juice ginger and lemon and add it to hot water. You may add cardomom.",
          "strInstructionsES": null,
          "strInstructionsDE": "Ingwer und Zitrone entsaften und in heißes Wasser geben. Du kannst Cardomom hinzufügen.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Spremere lo zenzero e il limone e aggiungerlo all'acqua calda.Puoi aggiungere il cardamomo.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/7j1z2e1487603414.jpg",
          "strIngredient1": "Ginger",
          "strIngredient2": "Lemon",
          "strIngredient3": "Water",
          "strIngredient4": null,
          "strIngredient5": null,
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "1 inch ",
          "strMeasure2": "1/4 ",
          "strMeasure3": "1 cup hot ",
          "strMeasure4": null,
          "strMeasure5": null,
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2017-02-20 15:10:15"
      },
      {
          "idDrink": "17832",
          "strDrink": "A Night In Old Mandalay",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Highball glass",
          "strInstructions": "In a shaker half-filled with ice cubes, combine the light rum, añejo rum, orange juice, and lemon juice. Shake well. Strain into a highball glass almost filled with ice cubes. Top with the ginger ale. Garnish with the lemon twist.",
          "strInstructionsES": "En una coctelera llena hasta la mitad con cubitos de hielo, mezcla el ron blanco, el ron añejo, el jugo de naranja y el jugo de lima. Agita bien. Cuela la mezcla en un vaso alto casi lleno de cubitos de hielo. Cubra con la cerveza de jengibre. Decora con el twist de limón.",
          "strInstructionsDE": "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, den Light Rum, Aejo Rum, Orangensaft und Zitronensaft vermengen. Gut schütteln. In ein Highball-Glas abseihen, das fast mit Eiswürfeln gefüllt ist. Mit dem Ginger Ale bestreuen. Mit der Zitronenscheibe garnieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "In uno shaker riempito a metà con cubetti di ghiaccio, unire il rum light, il rum aejo, il succo d'arancia e il succo di limone. Agitare bene. Filtrare in un bicchiere highball quasi pieno di cubetti di ghiaccio. Completare con la ginger ale. Guarnire con la scorza di limone.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vyrvxt1461919380.jpg",
          "strIngredient1": "Light rum",
          "strIngredient2": "Añejo rum",
          "strIngredient3": "Orange juice",
          "strIngredient4": "Lemon juice",
          "strIngredient5": "Ginger ale",
          "strIngredient6": "Lemon peel",
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "1 oz ",
          "strMeasure2": "1 oz ",
          "strMeasure3": "1 oz ",
          "strMeasure4": "1/2 oz ",
          "strMeasure5": "3 oz ",
          "strMeasure6": "1 twist of ",
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2016-04-29 09:43:00"
      }
  ]
};

export { sampleRawDrinkData };